```{r}
install.packages("operators")
library("operators")
install.packages("pheatmap")
library("pheatmap")
install.packages("ggplot2")
library("ggplot2")
install.packages("dplyr")
library("dplyr")
install.packages("grid")
library("grid")
allDepMapData = readRDS("/Users/Amanda/Desktop/DepMap19Q1_allData.RDS")
brain.anno = allDepMapData$annotation[allDepMapData$annotation$Subtype.Disease == "Glioblastoma", ]
rownames(brain.anno) = brain.anno$DepMap_ID
brain.anno = brain.anno[, -1]
cell.lines = dput(rownames(brain.anno))
exp.clean = allDepMapData$expression[, -which(colnames(allDepMapData$expression) %!in% cell.lines)]
copy.clean = allDepMapData$copynumber[, -which(colnames(allDepMapData$copynumber) %!in% cell.lines)]
relevant.mutations = subset(allDepMapData$mutation, names(allDepMapData$mutation) %in% cell.lines)
ceres.clean = allDepMapData$kd.ceres[, -which(colnames(allDepMapData$kd.ceres) %!in% cell.lines)]
prob.clean = allDepMapData$kd.prob[, -which(colnames(allDepMapData$kd.prob) %!in% cell.lines)]
sum(is.na(ceres.clean))
sum(is.na(prob.clean))
sum(is.na(copy.clean))
sum(is.na(exp.clean))
sum(is.na(relevant.mutations))
copy.clean = copy.clean[-which(apply(copy.clean, 1, function(x) {sum(is.na(x))}) > 0), ]
sum(is.na(copy.clean))
sum(exp.clean < 0)
sum(prob.clean < 0)
sum(prob.clean > 1)
sum(ceres.clean == 0) 
sum(prob.clean == 0) 
sum(copy.clean == 0)
sum(exp.clean == 0)
dim(copy.clean) == dim(exp.clean)
gene.data.co = c(rownames(copy.clean))
gene.data.ex = c(rownames(exp.clean))
exp.clean = exp.clean[-which(rownames(exp.clean) %!in% gene.data.co),]
copy.clean = copy.clean[-which(rownames(copy.clean) %!in% gene.data.ex),]
genes.clean = rownames(exp.clean)
ceres.clean = ceres.clean[-which(rownames(ceres.clean) %!in% genes.clean),]
prob.clean = prob.clean[-which(rownames(prob.clean) %!in% genes.clean),]
genes.clean = rownames(ceres.clean)
exp.clean = exp.clean[-which(rownames(exp.clean) %!in% genes.clean),]
copy.clean = copy.clean[-which(rownames(copy.clean) %!in% genes.clean),]
rm(gene.data.co)
rm(gene.data.ex)
brain.anno$CCLE_Name = factor(brain.anno$CCLE_Name)
brain.anno$Aliases = factor(brain.anno$Aliases)
brain.anno$Primary.Disease = factor(brain.anno$Primary.Disease)
brain.anno$Subtype.Disease = factor(brain.anno$Subtype.Disease)
brain.anno$Subtype.Gender = factor(brain.anno$Gender)
brain.anno$Subtype.Source = factor(brain.anno$Source)
ceres.clean = ceres.clean[order(rownames(ceres.clean)), order(colnames(ceres.clean))]
prob.clean = prob.clean[order(rownames(prob.clean)), order(colnames(prob.clean))]
exp.clean = exp.clean[order(rownames(exp.clean)), order(colnames(exp.clean))]
copy.clean = copy.clean[order(rownames(copy.clean)), order(colnames(copy.clean))]
relevant.mutations.combi = do.call(rbind, lapply(which(names(allDepMapData$mutation) %in% cell.lines), function(a) allDepMapData$mutation[[a]]))
common.genes = as.matrix(table(c(relevant.mutations.combi$Hugo_Symbol)))
summary(common.genes)
#rownames(common.genes) = common.genes$Var1
#common.genes$Var1 = NULL
common.genes = as.matrix(common.genes)
barplot(common.genes, beside = T, names.arg = rownames(common.genes), las = 2)
common.genes.c = subset(common.genes, common.genes > 11)
common.genes.c = common.genes.c[c(6, 11, 10, 7, 4, 9, 3, 2, 1, 8),]
barplot_commongenes <- barplot(common.genes.c, beside = T, names.arg = rownames(common.genes.c), ylab = "Frequency", main = "Most common gene mutations", las = 2)
mutations.all = rbind(relevant.mutations$`ACH-000036`,relevant.mutations$`ACH-000040`, relevant.mutations$`ACH-000075`, relevant.mutations$`ACH-000098`, relevant.mutations$`ACH-000208`, relevant.mutations$`ACH-000215`, relevant.mutations$`ACH-000137`, relevant.mutations$`ACH-000152`, relevant.mutations$`ACH-000591`, relevant.mutations$`ACH-000673`, relevant.mutations$`ACH-000231`, relevant.mutations$`ACH-000244`, relevant.mutations$`ACH-000760`, relevant.mutations$`ACH-000368`, relevant.mutations$`ACH-000376`, relevant.mutations$`ACH-000445`, relevant.mutations$`ACH-000464`, relevant.mutations$`ACH-000469`, relevant.mutations$`ACH-000479`, relevant.mutations$`ACH-000570`, relevant.mutations$`ACH-000571`, relevant.mutations$`ACH-000623`, relevant.mutations$`ACH-000631`, relevant.mutations$`ACH-000738`, relevant.mutations$`ACH-000756`, relevant.mutations$`ACH-000819`, relevant.mutations$`ACH-000128`, relevant.mutations$`ACH-000887`$Hugo_Symbol)
list.cells = subset(mutations.all, mutations.all$Hugo_Symbol %in% rownames(common.genes.c))
unique(list.cells$DepMap_ID)
list.mtnd5 = unique(subset(mutations.all, mutations.all$Hugo_Symbol == "MT-ND5"))
cells.mtnd5 = c(list.mtnd5$DepMap_ID)
list.non_mtnd5 = unique(subset(mutations.all, mutations.all$Hugo_Symbol != "MT-ND5"))
cells.non_mtnd5 = c(list.non_mtnd5$DepMap_ID)
list.muc16 = unique(subset(mutations.all, mutations.all$Hugo_Symbol == "MUC16"))
cells.muc16 = c(list.muc16$DepMap_ID)
list.non_muc16 = unique(subset(mutations.all, mutations.all$Hugo_Symbol != "MUC16"))
cells.non_muc16 = c(list.non_muc16$DepMap_ID)
list.tp53 = unique(subset(mutations.all, mutations.all$Hugo_Symbol == "TP53"))
cells.tp53 = c(list.tp53$DepMap_ID)
list.non_tp53 = unique(subset(mutations.all, mutations.all$Hugo_Symbol != "TP53"))
cells.non_tp53 = c(list.non_tp53$DepMap_ID)
list.ttn = unique(subset(mutations.all, mutations.all$Hugo_Symbol == "TTN"))
cells.ttn = c(list.ttn$DepMap_ID)
list.non_ttn = unique(subset(mutations.all, mutations.all$Hugo_Symbol != "TTN"))
cells.non_ttn = c(list.non_ttn$DepMap_ID)
exp.mtnd5 = exp.clean[,which(colnames(exp.clean) %in% cells.mtnd5)]
copy.mtnd5 = copy.clean[,which(colnames(copy.clean) %in% cells.mtnd5)]
ceres.mtnd5 = ceres.clean[,which(colnames(ceres.clean) %in% cells.mtnd5)]
prob.mtnd5 = prob.clean[,which(colnames(prob.clean) %in% cells.mtnd5)]
exp.non_mtnd5 = exp.clean[,which(colnames(exp.clean) %in% cells.non_mtnd5)]
copy.non_mtnd5 = copy.clean[,which(colnames(copy.clean) %in% cells.non_mtnd5)]
ceres.non_mtnd5 = ceres.clean[,which(colnames(ceres.clean) %in% cells.non_mtnd5)]
prob.non_mtnd5 = prob.clean[,which(colnames(prob.clean) %in% cells.non_mtnd5)]
exp.muc16 = exp.clean[,which(colnames(exp.clean) %in% cells.muc16)]
copy.muc16 = copy.clean[,which(colnames(copy.clean) %in% cells.muc16)]
ceres.muc16 = ceres.clean[,which(colnames(ceres.clean) %in% cells.muc16)]
prob.muc16 = prob.clean[,which(colnames(prob.clean) %in% cells.muc16)]
exp.non_muc16 = exp.clean[,which(colnames(exp.clean) %in% cells.non_muc16)]
copy.non_muc16 = copy.clean[,which(colnames(copy.clean) %in% cells.non_muc16)]
ceres.non_muc16 = ceres.clean[,which(colnames(ceres.clean) %in% cells.non_muc16)]
prob.non_muc16 = prob.clean[,which(colnames(prob.clean) %in% cells.non_muc16)]
exp.tp53 = exp.clean[,which(colnames(exp.clean) %in% cells.tp53)]
copy.tp53 = copy.clean[,which(colnames(copy.clean) %in% cells.tp53)]
ceres.tp53 = ceres.clean[,which(colnames(ceres.clean) %in% cells.tp53)]
prob.tp53 = prob.clean[,which(colnames(prob.clean) %in% cells.tp53)]
exp.non_tp53 = exp.clean[,which(colnames(exp.clean) %in% cells.non_tp53)]
copy.non_tp53 = copy.clean[,which(colnames(copy.clean) %in% cells.non_tp53)]
ceres.non_tp53 = ceres.clean[,which(colnames(ceres.clean) %in% cells.non_tp53)]
prob.non_tp53 = prob.clean[,which(colnames(prob.clean) %in% cells.non_tp53)]
exp.ttn = exp.clean[,which(colnames(exp.clean) %in% cells.ttn)]
copy.ttn = copy.clean[,which(colnames(copy.clean) %in% cells.ttn)]
ceres.ttn = ceres.clean[,which(colnames(ceres.clean) %in% cells.ttn)]
prob.ttn = prob.clean[,which(colnames(prob.clean) %in% cells.ttn)]
exp.non_ttn = exp.clean[,which(colnames(exp.clean) %in% cells.non_ttn)]
copy.non_ttn = copy.clean[,which(colnames(copy.clean) %in% cells.non_ttn)]
ceres.non_ttn = ceres.clean[,which(colnames(ceres.clean) %in% cells.non_ttn)]
prob.non_ttn = prob.clean[,which(colnames(prob.clean) %in% cells.non_ttn)]

mtnd5.exp.mean = as.matrix(c(rowMeans(exp.mtnd5)))
mtnd5.copy.mean = as.matrix(c(rowMeans(copy.mtnd5)))
mtnd5.ceres.mean = as.matrix(c(rowMeans(ceres.mtnd5)))
mtnd5.prob.mean = as.matrix(c(rowMeans(prob.mtnd5)))
non_mtnd5.exp.mean = as.matrix(c(rowMeans(exp.non_mtnd5)))
non_mtnd5.copy.mean = as.matrix(c(rowMeans(copy.non_mtnd5)))
non_mtnd5.ceres.mean = as.matrix(c(rowMeans(ceres.non_mtnd5)))
non_mtnd5.prob.mean = as.matrix(c(rowMeans(prob.non_mtnd5)))
muc16.exp.mean = as.matrix(c(rowMeans(exp.muc16)))
muc16.copy.mean = as.matrix(c(rowMeans(copy.muc16)))
muc16.ceres.mean = as.matrix(c(rowMeans(ceres.muc16)))
muc16.prob.mean = as.matrix(c(rowMeans(prob.muc16)))
non_muc16.exp.mean = as.matrix(c(rowMeans(exp.non_muc16)))
non_muc16.copy.mean = as.matrix(c(rowMeans(copy.non_muc16)))
non_muc16.ceres.mean = as.matrix(c(rowMeans(ceres.non_muc16)))
non_muc16.prob.mean = as.matrix(c(rowMeans(prob.non_muc16)))
tp53.exp.mean = as.matrix(c(rowMeans(exp.tp53)))
tp53.copy.mean = as.matrix(c(rowMeans(copy.tp53)))
tp53.ceres.mean = as.matrix(c(rowMeans(ceres.tp53)))
tp53.prob.mean = as.matrix(c(rowMeans(prob.tp53)))
non_tp53.exp.mean = as.matrix(c(rowMeans(exp.non_tp53)))
non_tp53.copy.mean = as.matrix(c(rowMeans(copy.non_tp53)))
non_tp53.ceres.mean = as.matrix(c(rowMeans(ceres.non_tp53)))
non_tp53.prob.mean = as.matrix(c(rowMeans(prob.non_tp53)))
ttn.exp.mean = as.matrix(c(rowMeans(exp.ttn)))
ttn.copy.mean = as.matrix(c(rowMeans(copy.ttn)))
ttn.ceres.mean = as.matrix(c(rowMeans(ceres.ttn)))
ttn.prob.mean = as.matrix(c(rowMeans(prob.ttn)))
non_ttn.exp.mean = as.matrix(c(rowMeans(exp.non_ttn)))
non_ttn.copy.mean = as.matrix(c(rowMeans(copy.non_ttn)))
non_ttn.ceres.mean = as.matrix(c(rowMeans(ceres.non_ttn)))
non_ttn.prob.mean = as.matrix(c(rowMeans(prob.non_ttn)))
boxplot_expression <- boxplot(exp.clean, ylab ="Expression level", main = "Distribution of expression", par(las =2))
boxplot_CN <- boxplot(copy.clean, ylab = "Copy number", main = "Distribution of copy number", par(las=2))
boxplot_mtnd5_exp <- boxplot(mtnd5.exp.mean, ylab = "Expression level", main = "Mean expression of all genes containing MT-ND5 as DM")
boxplot_mtnd5_CN <- boxplot(mtnd5.copy.mean, ylab = "Copy number", main = "Mean copy number of all genes containing MT-ND5 as DM")
library(grid)
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(exp.clean, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(exp.clean.w0, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(copy.clean, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(copy.clean.w0, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(ceres.clean, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(ceres.clean.w0, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(prob.clean, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
#pheatmap(prob.clean.w0, show_rownames = F)
setHook("grid.newpage", NULL, "replace")
grid.text("celllines", y=-0.07, gp=gpar(fontsize=16))
grid.text("genes", x=-0.07, rot=90, gp=gpar(fontsize=16))
```

```{r}
sum(exp.clean == 0)
exp.clean.w0 <- exp.clean[!(apply(exp.clean, 1, function(y) any(y == 0))),]
sum(exp.clean.w0 == 0)
sum(copy.clean == 0)
copy.clean.w0 <- copy.clean[!(apply(copy.clean, 1, function(y) any(y == 0))),]
sum(copy.clean.w0 == 0)
sum(ceres.clean == 0)
ceres.clean.w0 <- ceres.clean[!(apply(ceres.clean, 1, function(y) any(y == 0))),]
sum(ceres.clean.w0 == 0)
sum(prob.clean == 0)
prob.clean.w0 <- prob.clean[!(apply(prob.clean, 1, function(y) any(y == 0))),]
sum(prob.clean.w0 == 0)
dim(copy.clean.w0) == dim(exp.clean.w0)
gene.data.ex = c(rownames(exp.clean.w0))
copy.clean.w0 = copy.clean.w0[-which(rownames(copy.clean.w0) %!in% gene.data.ex),]
genes.clean.w0 = rownames(exp.clean.w0)
ceres.clean.w0 = ceres.clean.w0[-which(rownames(ceres.clean.w0) %!in% genes.clean.w0),]
prob.clean.w0 = prob.clean.w0[-which(rownames(prob.clean.w0) %!in% genes.clean.w0),]
genes.clean.w0 = rownames(prob.clean.w0)
exp.clean.w0 = exp.clean.w0[-which(rownames(exp.clean.w0) %!in% genes.clean.w0),]
copy.clean.w0 = copy.clean.w0[-which(rownames(copy.clean.w0) %!in% genes.clean.w0),]
ceres.clean.w0 = ceres.clean.w0[-which(rownames(ceres.clean.w0) %!in% genes.clean.w0),]
rm(gene.data.ex)
pca_exp <- prcomp(t(exp.clean.w0), scale = TRUE) 
plot(pca_exp$x[,1], pca_exp$x[,2]) 
pca_exp_var <- pca_exp$sdev^2
pca_exp_var_per <- round(pca_exp_var/sum(pca_exp_var)*100, 1) 
barplot(pca_exp_var_per, main = "Proportion of variance", xlab = "Principal component", ylab = "Percent variation")
pca_data_exp <- data.frame(Sample = rownames(pca_exp$x), X = pca_exp$x[,1], Y = pca_exp$x[,2]) 
pca_data_exp
pca_exp_plot <- ggplot(data = pca_data_exp, aes(x=X, y=Y, label = Sample)) + geom_point() + xlab(paste("PC1 -", pca_exp_var_per[1], "%", sep = "")) + ylab(paste("PC2 -", pca_exp_var_per[2], "%", sep="")) + theme_bw() + ggtitle("PCA expression")
pca_exp_plot
loading_scores_exp <- pca_exp$rotation[,1]
gene_scores_exp <- abs(loading_scores_exp)
gene_score_exp_ranked <- sort(gene_scores_exp, decreasing = TRUE)
top_10_genes_exp <- names(gene_score_exp_ranked[1:10])
top_10_genes_exp
pca_exp$rotation[top_10_genes_exp,1]
pca_copy <- prcomp(t(copy.clean.w0), scale = TRUE) 
plot(pca_copy$x[,1], pca_copy$x[,2]) 
pca_copy_var <- pca_copy$sdev^2 
pca_copy_var_per <- round(pca_copy_var/sum(pca_copy_var)*100, 1) 
barplot(pca_copy_var_per, main = "Proportion of variance", xlab = "Principal component", ylab = "Percent variation")
pca_data_copy <- data.frame(Sample = rownames(pca_copy$x), X = pca_copy$x[,1], Y = pca_copy$x[,2]) 
pca_data_copy
pca_copy_plot <- ggplot(data = pca_data_copy, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_copy_var_per[1], "%", sep = ""))  + ylab(paste("PC2 -", pca_copy_var_per[2], "%", sep="")) + theme_bw() + ggtitle("PCA copy number") 
pca_copy_plot
loading_scores_copy <- pca_copy$rotation[,1]      
gene_scores_copy <- abs(loading_scores_copy)          
gene_score_copy_ranked <- sort(gene_scores_copy, decreasing = TRUE)
top_10_genes_copy <- names(gene_score_copy_ranked[1:10])
top_10_genes_copy
pca_copy$rotation[top_10_genes_copy,1]
pca_ceres <- prcomp(t(ceres.clean.w0), scale = TRUE) 
plot(pca_ceres$x[,1], pca_ceres$x[,2]) 
pca_ceres_var <- pca_ceres$sdev^2 
pca_ceres_var_per <- round(pca_ceres_var/sum(pca_ceres_var)*100, 1) 
barplot(pca_ceres_var_per, main = "Proportion of variance", xlab = "Principal component", ylab = "Percent variation")
pca_data_ceres_12 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,1], Y = pca_ceres$x[,2]) 
pca_data_ceres_12
pca_ceres_plot_12 <- ggplot(data = pca_data_ceres_12, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_ceres_var_per[1], "%", sep = ""))  + ylab(paste("PC2 -", pca_ceres_var_per[2], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_12
pca_data_ceres_13 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,1], Y = pca_ceres$x[,3]) 
pca_data_ceres_13
pca_ceres_plot_13 <- ggplot(data = pca_data_ceres_13, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_ceres_var_per[1], "%", sep = ""))  + ylab(paste("PC3 -", pca_ceres_var_per[3], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_13
pca_data_ceres_14 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,1], Y = pca_ceres$x[,4]) 
pca_data_ceres_14
pca_ceres_plot_14 <- ggplot(data = pca_data_ceres_14, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_ceres_var_per[1], "%", sep = ""))  + ylab(paste("PC4 -", pca_ceres_var_per[4], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_14
pca_data_ceres_15 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,1], Y = pca_ceres$x[,5]) 
pca_data_ceres_15
pca_ceres_plot_15 <- ggplot(data = pca_data_ceres_15, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_ceres_var_per[1], "%", sep = ""))  + ylab(paste("PC5 -", pca_ceres_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_15
pca_data_ceres_23 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,2], Y = pca_ceres$x[,3]) 
pca_data_ceres_23
pca_ceres_plot_23 <- ggplot(data = pca_data_ceres_23, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC2 -", pca_ceres_var_per[2], "%", sep = ""))  + ylab(paste("PC3 -", pca_ceres_var_per[3], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_23
pca_data_ceres_24 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,2], Y = pca_ceres$x[,4]) 
pca_data_ceres_24
pca_ceres_plot_24 <- ggplot(data = pca_data_ceres_24, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC2 -", pca_ceres_var_per[2], "%", sep = ""))  + ylab(paste("PC4 -", pca_ceres_var_per[4], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_24
pca_data_ceres_25 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,2], Y = pca_ceres$x[,5]) 
pca_data_ceres_25
pca_ceres_plot_25 <- ggplot(data = pca_data_ceres_25, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC2 -", pca_ceres_var_per[2], "%", sep = ""))  + ylab(paste("PC5 -", pca_ceres_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_25
pca_data_ceres_34 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,3], Y = pca_ceres$x[,4]) 
pca_data_ceres_34
pca_ceres_plot_34 <- ggplot(data = pca_data_ceres_34, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC3 -", pca_ceres_var_per[3], "%", sep = ""))  + ylab(paste("PC4 -", pca_ceres_var_per[4], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_34
pca_data_ceres_35 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,3], Y = pca_ceres$x[,5]) 
pca_data_ceres_35
pca_ceres_plot_35 <- ggplot(data = pca_data_ceres_35, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC3 -", pca_ceres_var_per[3], "%", sep = ""))  + ylab(paste("PC5 -", pca_ceres_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_35
pca_data_ceres_45 <- data.frame(Sample = rownames(pca_ceres$x), X = pca_ceres$x[,4], Y = pca_ceres$x[,5]) 
pca_data_ceres_45
pca_ceres_plot_45 <- ggplot(data = pca_data_ceres_45, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC4 -", pca_ceres_var_per[4], "%", sep = ""))  + ylab(paste("PC5 -", pca_ceres_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA ceres score")
pca_ceres_plot_45
loading_scores_ceres_1 <- pca_ceres$rotation[,1]      
gene_scores_ceres_1 <- abs(loading_scores_ceres_1)          
gene_score_ceres_ranked_1 <- sort(gene_scores_ceres_1, decreasing = TRUE)
top_10_genes_ceres_1 <- names(gene_score_ceres_ranked_1[1:10])
top_10_genes_ceres_1
pca_ceres$rotation[top_10_genes_ceres_1,1]
loading_scores_ceres_2 <- pca_ceres$rotation[,2]      
gene_scores_ceres_2 <- abs(loading_scores_ceres_2)          
gene_score_ceres_ranked_2 <- sort(gene_scores_ceres_2, decreasing = TRUE)
top_10_genes_ceres_2 <- names(gene_score_ceres_ranked_2[1:10])
top_10_genes_ceres_2
pca_ceres$rotation[top_10_genes_ceres_2,2]
loading_scores_ceres_3 <- pca_ceres$rotation[,3]      
gene_scores_ceres_3 <- abs(loading_scores_ceres_3)          
gene_score_ceres_ranked_3 <- sort(gene_scores_ceres_3, decreasing = TRUE)
top_10_genes_ceres_3 <- names(gene_score_ceres_ranked_3[1:10])
top_10_genes_ceres_3
pca_ceres$rotation[top_10_genes_ceres_3,3]
loading_scores_ceres_4 <- pca_ceres$rotation[,4]      
gene_scores_ceres_4 <- abs(loading_scores_ceres_4)          
gene_score_ceres_ranked_4 <- sort(gene_scores_ceres_4, decreasing = TRUE)
top_10_genes_ceres_4 <- names(gene_score_ceres_ranked_4[1:10])
top_10_genes_ceres_4
pca_ceres$rotation[top_10_genes_ceres_4,4]
loading_scores_ceres_5 <- pca_ceres$rotation[,5]      
gene_scores_ceres_5 <- abs(loading_scores_ceres_5)          
gene_score_ceres_ranked_5 <- sort(gene_scores_ceres_5, decreasing = TRUE)
top_10_genes_ceres_5 <- names(gene_score_ceres_ranked_5[1:10])
top_10_genes_ceres_5
pca_ceres$rotation[top_10_genes_ceres_5,5]
pca_prob <- prcomp(t(prob.clean.w0), scale = TRUE) 
plot(pca_prob$x[,1], pca_prob$x[,2]) 
pca_prob_var <- pca_prob$sdev^2 
pca_prob_var_per <- round(pca_prob_var/sum(pca_prob_var)*100, 1) 
barplot(pca_prob_var_per, main = "Proportion of variance", xlab = "Principal component", ylab = "Percent variation")
pca_data_prob_12 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,1], Y = pca_prob$x[,2]) 
pca_data_prob_12
pca_prob_plot_12 <- ggplot(data = pca_data_prob_12, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_prob_var_per[1], "%", sep = ""))  + ylab(paste("PC2 -", pca_prob_var_per[2], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_12
pca_data_prob_13 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,1], Y = pca_prob$x[,3]) 
pca_data_prob_13
pca_prob_plot_13 <- ggplot(data = pca_data_prob_13, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_prob_var_per[1], "%", sep = ""))  + ylab(paste("PC3 -", pca_prob_var_per[3], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_13
pca_data_prob_14 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,1], Y = pca_prob$x[,4]) 
pca_data_prob_14
pca_prob_plot_14 <- ggplot(data = pca_data_prob_14, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_prob_var_per[1], "%", sep = ""))  + ylab(paste("PC4 -", pca_prob_var_per[4], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_14
pca_data_prob_15 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,1], Y = pca_prob$x[,5]) 
pca_data_prob_15
pca_prob_plot_15 <- ggplot(data = pca_data_prob_15, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC1 -", pca_prob_var_per[1], "%", sep = ""))  + ylab(paste("PC5 -", pca_prob_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_15
pca_data_prob_23 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,2], Y = pca_prob$x[,3]) 
pca_data_prob_23
pca_prob_plot_23 <- ggplot(data = pca_data_prob_23, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC2 -", pca_prob_var_per[2], "%", sep = ""))  + ylab(paste("PC3 -", pca_prob_var_per[3], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_23
pca_data_prob_24 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,2], Y = pca_prob$x[,4]) 
pca_data_prob_24
pca_prob_plot_24 <- ggplot(data = pca_data_prob_24, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC2 -", pca_prob_var_per[2], "%", sep = ""))  + ylab(paste("PC4 -", pca_prob_var_per[4], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_24
pca_data_prob_25 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,2], Y = pca_prob$x[,5]) 
pca_data_prob_25
pca_prob_plot_25 <- ggplot(data = pca_data_prob_25, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC2 -", pca_prob_var_per[2], "%", sep = ""))  + ylab(paste("PC5 -", pca_prob_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_25
pca_data_prob_34 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,3], Y = pca_prob$x[,4]) 
pca_data_prob_34
pca_prob_plot_34 <- ggplot(data = pca_data_prob_34, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC3 -", pca_prob_var_per[3], "%", sep = ""))  + ylab(paste("PC4 -", pca_prob_var_per[4], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_34
pca_data_prob_35 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,3], Y = pca_prob$x[,5]) 
pca_data_prob_35
pca_prob_plot_35 <- ggplot(data = pca_data_prob_35, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC3 -", pca_prob_var_per[3], "%", sep = ""))  + ylab(paste("PC5 -", pca_prob_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_35
pca_data_prob_45 <- data.frame(Sample = rownames(pca_prob$x), X = pca_prob$x[,4], Y = pca_prob$x[,5]) 
pca_data_prob_45
pca_prob_plot_45 <- ggplot(data = pca_data_prob_45, aes(x=X, y=Y, label = Sample)) + geom_point()   + xlab(paste("PC4 -", pca_prob_var_per[4], "%", sep = ""))  + ylab(paste("PC5 -", pca_prob_var_per[5], "%", sep="")) + theme_bw() + ggtitle("PCA probability score")
pca_prob_plot_45
loading_scores_prob_1 <- pca_prob$rotation[,1]      
gene_scores_prob_1 <- abs(loading_scores_prob_1)          
gene_score_prob_ranked_1 <- sort(gene_scores_prob_1, decreasing = TRUE)
top_10_genes_prob_1 <- names(gene_score_prob_ranked_1[1:10])
top_10_genes_prob_1
pca_prob$rotation[top_10_genes_prob_1,1]
loading_scores_prob_2 <- pca_prob$rotation[,2]      
gene_scores_prob_2 <- abs(loading_scores_prob_2)          
gene_score_prob_ranked_2 <- sort(gene_scores_prob_2, decreasing = TRUE)
top_10_genes_prob_2 <- names(gene_score_prob_ranked_2[1:10])
top_10_genes_prob_2
pca_prob$rotation[top_10_genes_prob_2,2]
loading_scores_prob_3 <- pca_prob$rotation[,3]      
gene_scores_prob_3 <- abs(loading_scores_prob_3)          
gene_score_prob_ranked_3 <- sort(gene_scores_prob_3, decreasing = TRUE)
top_10_genes_prob_3 <- names(gene_score_prob_ranked_3[1:10])
top_10_genes_prob_3
pca_prob$rotation[top_10_genes_prob_3,3]
loading_scores_prob_4 <- pca_prob$rotation[,4]      
gene_scores_prob_4 <- abs(loading_scores_prob_4)          
gene_score_prob_ranked_4 <- sort(gene_scores_prob_4, decreasing = TRUE)
top_10_genes_prob_4 <- names(gene_score_prob_ranked_4[1:10])
top_10_genes_prob_4
pca_prob$rotation[top_10_genes_prob_4,4]
loading_scores_prob_5 <- pca_prob$rotation[,5]      
gene_scores_prob_5 <- abs(loading_scores_prob_5)          
gene_score_prob_ranked_5 <- sort(gene_scores_prob_5, decreasing = TRUE)
top_10_genes_prob_5 <- names(gene_score_prob_ranked_5[1:10])
top_10_genes_prob_5
pca_prob$rotation[top_10_genes_prob_5,5]
```

```{r}
mutations.tp53 = rbind(relevant.mutations$`ACH-000036`,relevant.mutations$`ACH-000040`, relevant.mutations$`ACH-000098`, relevant.mutations$`ACH-000208`, relevant.mutations$`ACH-000215`, relevant.mutations$`ACH-000137`, relevant.mutations$`ACH-000152`, relevant.mutations$`ACH-000591`, relevant.mutations$`ACH-000673`, relevant.mutations$`ACH-000231`, relevant.mutations$`ACH-000368`, relevant.mutations$`ACH-000376`, relevant.mutations$`ACH-000445`, relevant.mutations$`ACH-000464`, relevant.mutations$`ACH-000469`, relevant.mutations$`ACH-000570`, relevant.mutations$`ACH-000571`, relevant.mutations$`ACH-000623`, relevant.mutations$`ACH-000673`, relevant.mutations$`ACH-000738`, relevant.mutations$`ACH-000756`, relevant.mutations$`ACH-000819`, relevant.mutations$`ACH-000128`)
mutations.tp53= select(mutations.tp53, c(2,21, 36))
mutations.tp53 = subset(mutations.tp53, mutations.tp53$isDeleterious == "TRUE")
```

```{r}
mutations.ttn = rbind(relevant.mutations$`ACH-000040`, relevant.mutations$`ACH-000098`, relevant.mutations$`ACH-000231`, relevant.mutations$`ACH-000445`, relevant.mutations$`ACH-000464`, relevant.mutations$`ACH-000570`, relevant.mutations$`ACH-000623`, relevant.mutations$`ACH-000738`, relevant.mutations$`ACH-000756`, relevant.mutations$`ACH-000760`, relevant.mutations$`ACH-000819`, relevant.mutations$`ACH-000244`, relevant.mutations$`ACH-000479`, relevant.mutations$`ACH-000631`)
mutations.ttn= select(mutations.ttn, c(2,21, 36))

mutations.mtnd5 = rbind(relevant.mutations$`ACH-000040`, relevant.mutations$`ACH-000098`, relevant.mutations$`ACH-000075`, relevant.mutations$`ACH-000231`, relevant.mutations$`ACH-000244`, relevant.mutations$`ACH-000368`, relevant.mutations$`ACH-000445`, relevant.mutations$`ACH-000479`, relevant.mutations$`ACH-000570`, relevant.mutations$`ACH-000571`, relevant.mutations$`ACH-000591`, relevant.mutations$`ACH-000621`, relevant.mutations$`ACH-000738`, relevant.mutations$`ACH-000756`, relevant.mutations$`ACH-000819`)
mutations.mtnd5= select(mutations.mtnd5, c(2,21, 36))
```

```{r}
mutations.muc16 = rbind(relevant.mutations$`ACH-000036`, relevant.mutations$`ACH-000137`, relevant.mutations$`ACH-000152`, relevant.mutations$`ACH-000208`, relevant.mutations$`ACH-000231`, relevant.mutations$`ACH-000368`, relevant.mutations$`ACH-000376`, relevant.mutations$`ACH-000464`, relevant.mutations$`ACH-000571`, relevant.mutations$`ACH-000738`, relevant.mutations$`ACH-000756`, relevant.mutations$`ACH-000819`)
mutations.muc16= select(mutations.muc16, c(2,21, 36))
mutations.muc16 = subset(mutations.muc16, mutations.muc16$isDeleterious == "TRUE")

mutations.pten = rbind(relevant.mutations$`ACH-000036`, relevant.mutations$`ACH-000040`, relevant.mutations$`ACH-000075`, relevant.mutations$`ACH-000208`, relevant.mutations$`ACH-000215`, relevant.mutations$`ACH-000137`, relevant.mutations$`ACH-000152`, relevant.mutations$`ACH-000231`, relevant.mutations$`ACH-000244`, relevant.mutations$`ACH-000760`, relevant.mutations$`ACH-000376`, relevant.mutations$`ACH-000464`, relevant.mutations$`ACH-000570`, relevant.mutations$`ACH-000571`, relevant.mutations$`ACH-000623`, relevant.mutations$`ACH-000128`)
mutations.pten = select(mutations.pten, c(2,21, 36))
mutations.pten = subset(mutations.pten, mutations.pten$isDeleterious == "TRUE")

list.tp53.genes = unique(subset(mutations.tp53))
genes.tp53 <- c(list.tp53.genes$Hugo_Symbol)
ceres.tp53.genes <- ceres.clean[which(rownames(ceres.clean) %in% genes.tp53),]
```

```{r}
list.ttn.genes = unique(subset(mutations.ttn))
genes.ttn <- c(list.ttn.genes$Hugo_Symbol)
ceres.ttn.genes <- ceres.clean[which(rownames(ceres.clean) %in% genes.ttn),]

list.mtnd5.genes = unique(subset(mutations.mtnd5))
genes.mtnd5 <- c(list.mtnd5.genes$Hugo_Symbol)
ceres.mtnd5.genes <- ceres.clean[which(rownames(ceres.clean) %in% genes.mtnd5),]
```

```{r}
list.muc16.genes = unique(subset(mutations.muc16))
genes.muc16 <- c(list.muc16.genes$Hugo_Symbol)
ceres.muc16.genes <- ceres.clean[which(rownames(ceres.clean) %in% genes.muc16),]

list.pten.genes = unique(subset(mutations.pten))
genes.pten <- c(list.pten.genes$Hugo_Symbol)
ceres.pten.genes <- ceres.clean[which(rownames(ceres.clean) %in% genes.pten),]

qqnorm(ceres.tp53.genes$`ACH-000036`, main="QQ-Plot of CERES scores of all genes of cell line ACH-000036")
qqline(ceres.tp53.genes$`ACH-000036`, datax = FALSE, distribution = qnorm,
        probs = c(0.25, 0.75), qtype = 7)
shapiro.test(ceres.tp53.genes$`ACH-000036`)
ceres.allDM.genes=rbind(ceres.tp53.genes, ceres.ttn.genes, ceres.mtnd5.genes, ceres.muc16.genes)
lapply(ceres.allDM.genes,shapiro.test)
t(ceres.tp53.genes)->ceres.tp53.genes_t
t(ceres.mtnd5.genes)->ceres.mtnd5.genes_t
t(ceres.pten.genes) -> ceres.pten.genes_t

cor.ceres.tp53.genes_t<-cor(ceres.tp53.genes_t, method="spearman")
cor.ceres.tp.53.only<-cor.ceres.tp53.genes_t[1:734,642]
cor.ceres.muc16.genes_t<-cor(ceres.muc16.genes_t, method="spearman")
cor.ceres.muc16.only<-cor.ceres.muc16.genes_t[1:478,251]
cor.ceres.pten.genes_t<-cor(ceres.pten.genes_t, method="spearman")
cor.ceres.pten.only<-cor.ceres.pten.genes_t[1:505,328]

install.packages("Hmisc")
library(Hmisc)

sig.cor.ceres.tp53.genes_t<-rcorr(as.matrix(ceres.tp53.genes_t), type="spearman")
sig.cor.ceres.tp53.only <-as.data.frame(sig.cor.ceres.tp53.genes_t$r[1:734, 642])
colnames(sig.cor.ceres.tp53.only) <- c("Correlation to TP53")

sig.cor.ceres.muc16.genes_t <-rcorr(as.matrix(ceres.muc16.genes_t), type="spearman")
sig.cor.ceres.muc16.only <-as.data.frame(sig.cor.ceres.muc16.genes_t$r[1:478, 251])
colnames(sig.cor.ceres.muc16.only) <- c("Correlation to MUC-16")

sig.cor.ceres.pten.genes_t <-rcorr(as.matrix(ceres.pten.genes_t), type="spearman")
sig.cor.ceres.pten.only <-as.data.frame(sig.cor.ceres.pten.genes_t$r[1:505, 328])
colnames(sig.cor.ceres.pten.only) <- c("Correlation to PTEN")

mlr.mat = as.data.frame(cbind(rowMeans(exp.clean.w0), rowMeans(copy.clean.w0), rowMeans(ceres.clean.w0), rowMeans(prob.clean.w0)))
colnames(mlr.mat) = c("expression", "copynumber", "ceres", "probability")
summary(lm(expression ~ ., data = mlr.mat))
summary(lm(copynumber ~ ., data = mlr.mat))
summary(lm(ceres ~ ., data = mlr.mat))
summary(lm(probability ~ ., data = mlr.mat))
```

```{r}
mlr.mat.0 = as.data.frame(cbind(rowMeans(exp.clean), rowMeans(copy.clean), rowMeans(ceres.clean), rowMeans(prob.clean)))
colnames(mlr.mat.0) = c("expression", "copynumber", "ceres", "probability")
summary(lm(expression ~ ., data = mlr.mat.0))
summary(lm(copynumber ~ ., data = mlr.mat.0))
summary(lm(ceres ~ ., data = mlr.mat.0))
summary(lm(probability ~ ., data = mlr.mat.0))
```

```{r}
library(caTools)
set.seed(123)
split.exp = sample.split(mlr.mat$expression, SplitRatio = 0.8)
split.exp = as.data.frame(split.exp)
training_set_exp = subset(mlr.mat, split.exp == TRUE)
test_set_exp = subset(mlr.mat, split.exp == FALSE)

training_set_exp = scale(training_set_exp)
test_set_exp = scale(test_set_exp)

set.seed(123)
split.copy = sample.split(mlr.mat$copynumber, SplitRatio = 0.8)
split.copy = as.data.frame(split.copy)
training.set.copy = subset(mlr.mat, split.copy == TRUE)
test.set.copy = subset(mlr.mat, split.copy == FALSE)

set.seed(123)
split.ceres = sample.split(mlr.mat$ceres, SplitRatio = 0.8)
training.set.ceres = subset(mlr.mat, split.ceres == TRUE)
test.set.ceres = subset(mlr.mat, split.ceres == FALSE)

set.seed(123)
split.prob = sample.split(mlr.mat$probability, SplitRatio = 0.8)
training.set.prob = subset(mlr.mat, split.prob ==TRUE)
test.set.prob = subset(mlr.mat, split.prob == FALSE)

exp.regressor = lm(expression ~ ., data = training_set_exp)
ceres.regressor = lm(ceres ~ ., data = as.data.frame(training.set.ceres))
prob.regressor = lm(probability ~., data = as.data.frame(training.set.prob))

exp_pred = predict(exp.regressor, newdata = test_set_exp) 
test_set_exp$Prediction = exp_pred

ceres_pred = predict(ceres.regressor, newdata = test.set.ceres)
test.set.ceres$Prediction = ceres_pred

prob_pred = predict(prob.regressor, newdata = test.set.prob)
test.set.prob$Prediction = prob_pred
```

```{r}
plot(density(test_set_exp$expression), col = "red")
lines(density(test_set_exp$Prediction), col = "blue")
plot(density(test.set.ceres$ceres), col = "red")
lines(density(test.set.ceres$Prediction))
plot(density(test.set.prob$probability), col = "red")
lines(density(test.set.prob$Prediction))
plot.ceres.m <- melt(test.set.ceres$ceres)
a <- melt(test.set.ceres$Prediction)
colnames(plot.ceres.m) <- "CERES"
rownames(plot.ceres.m) = rownames(test.set.ceres)
colnames(a) <- "Prediction"
plot.ceres.m <- cbind(plot.ceres.m,a)
plottingData.ceres <- melt(plot.ceres.m)
```

```{r}
library(reshape2)
library(ggplot2)

plot.exp.m <- melt(test_set_exp$expression)
a <- melt(test_set_exp$Prediction)
colnames(plot.exp.m) <- "Expression"
rownames(plot.exp.m) = rownames(plot.ceres.m)
colnames(a) <- "Prediction"
plot.exp.m <- cbind(plot.exp.m,a)
plottingData.exp <- melt(plot.exp.m)

exp_plot <- ggplot(data = plottingData.exp, aes(x=value, fill=variable)) + 
  geom_density(alpha=.3) +
  ggtitle(paste0("Performance evaluation Lin.Reg. expression")) +
  ylab("Density") +
  xlab("Expression values") +
  theme_bw(base_size = 7) +
  theme(legend.position="bottom",
        legend.direction="horizontal",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.title= element_blank(),
        axis.title.x = element_blank(),
        strip.text.y = element_text(angle = 0))

plot.ceres.m <- melt(test.set.ceres$ceres)
a <- melt(test.set.ceres$Prediction)
colnames(plot.ceres.m) <- "CERES"
rownames(plot.ceres.m) = rownames(test.set.ceres)
colnames(a) <- "Prediction"
plot.ceres.m <- cbind(plot.ceres.m,a)
plottingData.ceres <- melt(plot.ceres.m)

ceres_plot <- ggplot(data = plottingData.ceres, aes(x=value, fill=variable)) + 
  geom_density(alpha=.3) +
  ggtitle(paste0("Performance evaluation Lin.Reg. CERES score")) +
  ylab("Density") +
  xlab("CERES score values") +
  theme_bw(base_size = 7) +
  theme(legend.position="bottom",
        legend.direction="horizontal",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.title= element_blank(),
        axis.title.x = element_blank(),
        strip.text.y = element_text(angle = 0))

plot.prob.m <- melt(test.set.prob$probability)
a <- melt(test.set.prob$Prediction)
colnames(plot.prob.m) <- "Probability"
rownames(plot.prob.m) = rownames(test.set.prob)
colnames(a) <- "Prediction"
plot.prob.m <- cbind(plot.prob.m,a)
plottingData.prob <- melt(plot.prob.m)

prob_plot <- ggplot(data = plottingData.prob, aes(x=value, fill=variable)) + 
    geom_density(alpha=.3) +
     ggtitle(paste0("Performance evaluation Lin.Reg. probability")) +
     ylab("Density") +
     xlab("Probability values") +
    theme_bw(base_size = 7) +
     theme(legend.position="bottom",
           legend.direction="horizontal",
           plot.title = element_text(hjust = 0.5),
           axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
           legend.title= element_blank(),
           axis.title.x = element_blank(),
           strip.text.y = element_text(angle = 0))
```